export const ERROR_STATUS = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZE: 'UNAUTHORIZE',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  SERVER_ERROR: 'SERVER_ERROR',
} as const
