name: CD
run-name: ${{ github.workflow }} based on ${{ github.ref_name }}
on: # アクションのトリガータイミングを修正する場合は以下を修正
  push:
    branches: ['main']
  workflow_dispatch:
permissions: # GitHub Pagesへの公開権限を付与
  contents: read
  pages: write
  id-token: write
concurrency: # 連続でフローが動いた時に重複する処理を停止する
  group: 'pages'
  cancel-in-progress: true
jobs:
  build:
    name: Build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Volta Action
        uses: volta-cli/action@v4
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # ビルドファイルの吐き出し先
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4