name: CI
run-name: ${{ github.workflow }} on PR:${{ github.ref_name }} by ${{ github.actor }}'s change.
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: UT
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # PRへのカバレッジ出力権限を付与
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Volta Action
        uses: volta-cli/action@v4
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Report Coverage
        if: always() # テスト失敗時もカバレッジは出力する
        uses: davelosert/vitest-coverage-report-action@v2